/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import controller.Kontroler;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.Predmet;
import model.Profesor;

/**
 *
 * @author Omnix
 */
public class GlavnaForma extends javax.swing.JFrame {
      private String emailOsnivaca;
      private String korisnik;
      private Kontroler kontroler;
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }
    
    public GlavnaForma(String korisnik, String email) {
        initComponents();
        kontroler = Kontroler.getInstance();
        popuniComboBoxProfesora();
        ModelTabelePredmeta mtp = new ModelTabelePredmeta(new ArrayList<>());
        tblPredmeti.setModel(mtp);
        this.emailOsnivaca = email;
        this.korisnik = korisnik;
        jLabel1.setText(jLabel1.getText() + " " + korisnik);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUnesiProfesora = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnUnesiPredmet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPredmeti = new javax.swing.JTable();
        cmbProfesori = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnPopuniTabelu = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dobrodosli:");

        btnUnesiProfesora.setText("Unesi profesora");
        btnUnesiProfesora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiProfesoraActionPerformed(evt);
            }
        });

        btnUnesiPredmet.setText("Unesi predmet");
        btnUnesiPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiPredmetActionPerformed(evt);
            }
        });

        tblPredmeti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPredmeti);

        jLabel3.setText("Profesor za filtriranje:");

        btnPopuniTabelu.setText("Prikazi predmete profesora");
        btnPopuniTabelu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopuniTabeluActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi predmet");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPopuniTabelu)
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 34, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(cmbProfesori, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(84, 84, 84))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnUnesiPredmet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnUnesiProfesora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbProfesori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPopuniTabelu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUnesiPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesiProfesora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiProfesoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiProfesoraActionPerformed
        ProfesorForma pf = new ProfesorForma(this, false, emailOsnivaca);
        pf.setVisible(true);
    }//GEN-LAST:event_btnUnesiProfesoraActionPerformed

    private void btnUnesiPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiPredmetActionPerformed
        PredmetForma pf = new PredmetForma(this, false);
        pf.setVisible(true);
    }//GEN-LAST:event_btnUnesiPredmetActionPerformed

    private void btnPopuniTabeluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopuniTabeluActionPerformed
        List<Predmet> listaPredmeta = new ArrayList<>();
        Profesor izabraniProfesor = (Profesor) cmbProfesori.getSelectedItem();
        listaPredmeta = kontroler.napuniTabeluPredmeta(izabraniProfesor);
        
        ModelTabelePredmeta mtp = new ModelTabelePredmeta(listaPredmeta);
        tblPredmeti.setModel(mtp);
    }//GEN-LAST:event_btnPopuniTabeluActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int selectedRow = tblPredmeti.getSelectedRow();
        
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Molimo Vas izaberite neki predmet za brisanje.", "Izaberite predmet", JOptionPane.ERROR_MESSAGE);
        } else {
            ModelTabelePredmeta mtp = (ModelTabelePredmeta)tblPredmeti.getModel();
            int id = mtp.getListaPredmeta().get(selectedRow).getId();
            kontroler.obrisiPredmet(id);
            JOptionPane.showMessageDialog(this, "Brisanje predmeta je uspesno obavljeno!.", "Uspesna operacija brisanja", JOptionPane.INFORMATION_MESSAGE);
            osveziTabelu();
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPopuniTabelu;
    private javax.swing.JButton btnUnesiPredmet;
    private javax.swing.JButton btnUnesiProfesora;
    private javax.swing.JComboBox<Profesor> cmbProfesori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPredmeti;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBoxProfesora() {
        cmbProfesori.removeAllItems();
        List<Profesor> listaProfesora = kontroler.uzmiListuProfesora();
        for(Profesor p : listaProfesora){
            cmbProfesori.addItem(p);
        }
    }

    private void osveziTabelu() {
        List<Predmet> listaPredmeta = new ArrayList<>();
        Profesor izabraniProfesor = (Profesor) cmbProfesori.getSelectedItem();
        listaPredmeta = kontroler.napuniTabeluPredmeta(izabraniProfesor);
        
        ModelTabelePredmeta mtp = new ModelTabelePredmeta(listaPredmeta);
        tblPredmeti.setModel(mtp);
    }
}
